services:
  - type: web
    name: omid-portfolio
    env: python
    runtime: python3
    buildCommand: ""
    startCommand: "streamlit run app1.py --server.port=$PORT --server.address=0.0.0.0"
    plan: free

